basic:
  disablePermissions: false
  checkForUpdates: true

log:
  debugSpam: false
  anonymousMetrics: true

titles:
  useTitlesInsteadOfChat: true
  useActionBar: true
  titleFadeInTime: 20
  titleStayTime: 140
  titleFadeOutTime: 20

colors:
  infoColor: GOLD
  errorColor: RED

chunks:
  maxChunksClaimed: 50
  particlesWhenClaiming: true
  automaticUnclaimSeconds: -1
  unclaimCheckIntervalTicks: 1200
  displayNameOfOwner: true
  defaultSendAlertsToOwner: true
  maxPerListPage: 5
  disabledWorlds: []

protection:
  blockUnclaimedChunks: false
  blockPlayerChanges: true
  blockInteractions: true
  blockTnt: true
  blockCreeper: true
  blockWither: true
  protectAnimals: true
  blockPvp: false
  blockedCmds: []
  disableOfflineProtect: false

worldguard:
  allowClaimsInRegionsByDefault: true
  allowClaimingInNonGuardedWorlds: true
  allowAdminOverride: true

economy:
  useEconomy: true
  claimPrice: 100.0
  unclaimReward: 10.0
  firstFreeChunks: 0

data:
  saveDataInterval: 5
  keepJsonBackups: true

database:
  useDatabase: false
  groupRequests: true
  convertOldData: true
  hostname: '127.0.0.1'
  port: 3306
  database: 'MyServer'
  username: 'root'
  password: 'root'
  printDebug: false
