titles:
  useTitlesInsteadOfChat: true
  titleFadeInTime: 20
  titleStayTime: 140
  titleFadeOutTime: 20

colors:
  errorColor: RED
  successColor: GREEN
  infoColor: GOLD

chunks:
  maxChunksClaimed: 50
  particlesWhenClaiming: true
  automaticUnclaimSeconds: -1
  unclaimCheckIntervalTicks: 1200
  displayNameOfOwner: true

protection:
  blockUnclaimedChunks: false
  blockPlayerChanges: true
  blockTnt: true
  blockCreeper: true
  protectAnimals: true

economy:
  useEconomy: true
  claimPrice: 100.0
  unclaimReward: 10.0
  firstFree: true

data:
  saveDataInterval: 5

database:
  useDatabase: false
  hostname: '127.0.0.1'
  port: 3306
  database: 'MyServer'
  username: 'root'
  password: ''

messages:
  noPluginPerm: 'You do not have permission to use ClaimChunk.'
  claimNoPerm: 'You do not have permission to claim chunks.'
  claimAlreadyOwned: 'This chunk is already claimed.'
  claimTooMany: 'You own the maximum number of chunks.'
  claimSuccess: 'Chunk claimed!'
  claimFree: 'First chunk is free!'
  claimNotEnoughMoney: 'You do not have enough money.'
  unclaimNoPerm: 'You do not have permission to unclaim chunks.'
  unclaimNotOwned: 'This chunk is not owned.'
  unclaimNotOwner: 'You do not own this chunk.'
  unclaimSuccess: 'Chunk unclaimed!'
  unclaimRefund: 'You have been refunded %%AMT%%.'
  accessNoPerm: 'You do not have permission to give access to chunks.'
  accessHelp: 'Gives <player> access to interact with all blocks in your claimed chunks.'
  accessHas: '%%PLAYER%% now has access to your chunks.'
  accessNoLongerHas: '%%PLAYER%% no longer has access to your chunks.'
  accessNoPlayer: 'That player has not joined the server before.'
  accessOneself: 'You already have access to your own chunks.'
  nameClear: 'Your name has been cleared.'
  nameNotSet: 'You do not have a custom name set.'
  nameSet: 'Your name has been set: %%NAME%%.'
  chunkOwner: 'Entering the territory of %%PLAYER%%.'
  chunkSelf: 'Entering your own territory.'
  chunkLeave: 'Entering unclaimed territory.'
  chunkNoEdit: 'You cannot edit this chunk.'
  autoNoPerm: 'You may not auto-claim chunks.'
  autoEnabled: 'Automatic claiming enabled.'
  autoDisabled: 'Automatic claiming disabled.'
  reloadNoPerm: 'You do not have permission to use that sub command'
